# Generated by Django 4.2.3 on 2023-09-29 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=8, null=True)),
                ('age', models.PositiveIntegerField()),
                ('profession', models.CharField(choices=[('commerce', 'commerce'), ('Informatique', 'Informatique'), ('Armee', 'Armee')], max_length=12, null=True)),
                ('Langue', models.CharField(choices=[('Peulh', 'Peulh'), ('Moore', 'Moore'), ('Dioula', 'Dioula'), ('Anglais', 'Anglais'), ('Francais', 'Francais')], max_length=8, null=True)),
                ('region', models.CharField(choices=[('Centre-EST', 'Centre-EST'), ('Centre', 'Centre'), ('Centre-Ouest', 'Centre-Ouest'), ('Nord', 'Nord'), ('Sud', 'Sud')], max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_enregistres', models.ManyToManyField(to='appweb.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graphique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prospection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upfont_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.client')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appweb.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BooleanField(default=False)),
                ('Prospection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appweb.prospection')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_score', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.client')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.commercial')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('is_super', 'is_super'), ('is_commercial', 'is_commercial'), ('is_administrateur', 'is_administrateur')], default='is_commercial', max_length=17, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
