# Generated by Django 4.2.3 on 2023-10-14 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_remove_prospection_date_remove_prospection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospection',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.product'),
        ),
    ]
