# Generated by Django 4.2.3 on 2023-10-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_alter_prospection_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='genre',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Langue',
            new_name='langue',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='profession',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='groupname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='prospection',
            name='upfont_price',
        ),
        migrations.AddField(
            model_name='product',
            name='unlock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospection',
            name='upfront',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
