# Generated by Django 4.2.3 on 2023-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_rename_genre_client_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospection',
            name='predicted_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
