# Generated by Django 4.2.3 on 2023-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_prospection_predicted_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospection',
            name='predicted_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
