# Generated by Django 4.2.3 on 2023-10-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_prospection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospection',
            name='user',
        ),
    ]
